site_name: Deploying OpenShift on IBM Power Systems
#site_url: https://example.com/foo/
nav:
    - Home: 'index.md'
    - Deploying OpenShift on IBM Cloud Power Virtual Servers: ocp4-upi-powervs/README.md
    - Deploying OpenShift on IBM Cloud Power Virtual Servers via Bash Script: openshift-install-power/README.md
    - Deploying OpenShift on PowerVM managed via PowerVC: ocp4-upi-powervm/README.md
    - Deploying OpenShift on KVM: ocp4-upi-kvm/README.md

theme:
    name: readthedocs
markdown_extensions:
    - admonition
plugins:
    - search
